name: ecom
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
    androidX: true


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  google_sign_in: ^4.1.1
  shared_preferences: ^0.5.7+1
  fluttertoast: ^4.0.1
  firebase_auth: ^0.6.6
  cloud_firestore: ^0.8.2+3



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - images/m2.jpg
    - images/c1.jpg
    - images/m1.jpeg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/accessories.png
    - images/dress.png
    - images/formal.png
    - images/informal.png
    - images/jeans.png
    - images/shoe.png
    - images/tshirt.png
    - images/blazer1.jpeg
    - images/blazer2.jpeg
    - images/dress1.jpeg
    - images/dress2.jpeg
    - images/hills1.jpeg
    - images/hills2.jpeg
    - images/pants1.jpg
    - images/pants2.jpeg
    - images/shoe1.jpg
    - images/skt1.jpeg
    - images/skt2.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
